import type { NextPage } from 'next'
import Head from 'next/head'
import { InvoiceItem } from '../components/InvoiceItem'
import { Form } from '../components/Form'
import * as S from '../components/Pages/Index/Index.styles'
import { Sidebar } from '../components/Sidebar'
import { fakeData } from '../data'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <S.RootContainer>
        <div className='left'>
          <Sidebar />
          <Form />
        </div>
        <div className='right'>
          {fakeData.map((item) => {
            return (
              <InvoiceItem
                id={item.id}
                key={item.id}
                name={item.user.name}
                total={item.items.total}
                dueDate={item.dueDate}
                status={item.status}
              />
            )
          })}
        </div>
      </S.RootContainer>
    </div>
  )
}

export default Home
